# Generated by Django 5.2.15 on 2026-06-26 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_uploadeddocument_processing_completed_at_and_more'),
        ('extraction', '0003_alter_extractionrun_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='open', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20)),
                ('reason', models.TextField()),
                ('corrected_value', models.TextField(blank=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_review_tasks', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='documents.uploadeddocument')),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='extraction.extractionrun')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='extraction.extractedfield')),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['document', 'status'], name='review_revi_documen_0e9254_idx'), models.Index(fields=['assigned_to', 'status'], name='review_revi_assigne_11cdf4_idx')],
            },
        ),
    ]
