# Generated by Django 5.2.15 on 2026-06-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_uploadeddocument_processing_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=120)),
                ('raw_value', models.TextField(blank=True)),
                ('normalized_value', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_text', models.TextField(blank=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='documents.uploadeddocument')),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_review', 'Needs review')], default='running', max_length=30)),
                ('prompt_snapshot', models.TextField(blank=True)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(default='local-baseline', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='documents.uploadeddocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
