# Generated by Django 5.2.15 on 2026-06-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extraction', '0001_initial'),
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionrun',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_runs', to='schemas.extractionschema'),
        ),
        migrations.AddField(
            model_name='extractedfield',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='extraction.extractionrun'),
        ),
        migrations.AddIndex(
            model_name='extractedfield',
            index=models.Index(fields=['document', 'field_name'], name='extraction__documen_3fd008_idx'),
        ),
    ]
