# Generated by Django 5.2.15 on 2026-06-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_initial'),
        ('schemas', '0002_alter_extractionschema_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionrun',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_runs', to='schemas.extractionschema'),
        ),
    ]
