# Generated by Django 5.2.15 on 2026-06-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('processing', 'Processing'), ('processed', 'Processed'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('failed', 'Failed'), ('archived', 'Archived')], default='uploaded', max_length=30),
        ),
    ]
