# Generated by Django 5.2.15 on 2026-06-26 22:39

import apps.exports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_uploadeddocument_processing_completed_at_and_more'),
        ('extraction', '0003_alter_extractionrun_schema'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], max_length=20)),
                ('file', models.FileField(upload_to=apps.exports.models.export_upload_path)),
                ('field_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_records', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_records', to='documents.uploadeddocument')),
                ('extraction_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_records', to='extraction.extractionrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_records', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='exports_exp_workspa_a7fc93_idx'), models.Index(fields=['document', '-created_at'], name='exports_exp_documen_5ade0a_idx'), models.Index(fields=['format', '-created_at'], name='exports_exp_format_1d811a_idx')],
            },
        ),
    ]
